print("cadastro de aluno")
print("escreva a frase iniciar para começar")
iniciar=input()
print("quantos anos você tem?")
idade=int(input("idade: "))
print("qual é o seu nome?")
nome=input("nome: ")
print("qual é o seu curso?")
curso=input("curso: ")
print("cadastro concluído")
print(f"nome: {nome}")
print(f"idade: {idade}")
print(f"curso: {curso}")
print("obrigado por se cadastrar")
input("aperte enter para sair")